[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Carlos Olivares Reboredo <carlos.olivares.331@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
